---
- hosts: all
  tasks:
    - name: Add user name to git config
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_user_name }}"

    - name: Add user email to git config
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_user_email }}"
