---
- name: My Play
  hosts: all
  gather_facts: true
  tasks:
    - name: Install create-vite
      community.general.npm:
        name: create-vite
        version: 5.2.3
        path: node_modules
    - name: Delete package.json and package-lock.json created above
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - package.json
        - package-lock.json
    - name: Run create-vite
      ansible.builtin.command:
        cmd: npx create-vite my-app-template --template react
        creates: my-app-template
