---
- name: My Play
  hosts: all
  gather_facts: false
  vars:
    app_name: my-app-template
    create_vite_template: react-ts
    create_vite_command: npx create-vite {{ app_name }} --template {{ create_vite_template }}
  tasks:
    - name: Install create-vite
      community.general.npm:
        name: create-vite
        version: 5.2.3
        path: node_modules

    - name: Delete package.json and package-lock.json created above
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - package.json
        - package-lock.json

    - name: Run create-vite
      ansible.builtin.command:
        cmd: "{{ create_vite_command }}"
        creates: "{{ app_name }}"

    - name: Run git init
      ansible.builtin.command:
        cmd: git init
        chdir: "{{ app_name }}"
        creates: .git
      tags:
        - skip_ansible_lint

    - name: Add user name to git config
      community.general.git_config:
        name: user.name
        repo: "{{ app_name }}"
        scope: local
        value: 'CI User'

    - name: Add user email to git config
      community.general.git_config:
        name: user.email
        repo: "{{ app_name }}"
        scope: local
        value: 'ci-user@example.com'

    - name: First commit
      git_commit:
        commit_message: "My initial commit"
        chdir: "{{ app_name }}"

    - name: Create file
      ansible.builtin.shell:
        cmd: "echo foo >blah"
        chdir: "{{ app_name }}"
        creates: blah

    - name: Second commit
      git_commit:
        commit_message: "My initial commit 2"
        chdir: "{{ app_name }}"
