---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build and deploy template

jobs:
  build_template:
    name: Build template
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: "True"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c898ce22834cf40ea69adf6093755532df412102.tar.gz

      - name: download shell env
        run: nix-shell --run ls

      - name: ansible version
        run: nix-shell --run 'ansible --version'

      - name: run playbook
        run: nix-shell --run ./bin/ci

      - name: Clean for Upload artifact
        run: cd my-app-template && git clean -fxd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-template-artifact
          path: my-app-template

  deploy:
    name: Deploy to template repository
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: build_template
    if: ${{ github.ref == 'refs/heads/main' && needs.build_template.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: my-app-template-artifact
          path: my-app-template

      - name: Push to template repository
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$DEPLOY_KEY" | ssh-add - >/dev/null
          cd my-app-template
          git remote add origin \
            git@github.com:kisp/react-create-vite-extended-template.git
          git push -f -v origin master
